theme: jekyll-theme-minimal
title: ML/AI Portfolio
description: A showcase of my Machine Learning and Artificial Intelligence projects.
url: "https://ThomasDoesAI.github.io" # the base hostname & protocol for your site
markdown: kramdown
permalink: /:title/
collections:
  projects:
    output: true
    permalink: /projects/:title/
defaults:
  - scope:
      path: "_projects"
      type: "projects"
    values:
      layout: "post"
